/** App 端 UI 文案集中（✅ 庚-31／D-50）：依畫面分組；改文案只動此檔。
 * common 收跨畫面共用的通用文案（錯誤／狀態訊息、共用動作動詞、登入欄位）；
 * 其餘依畫面／區域分組。動態組字改為函式常數（見 elderDetail.remindersCount 等）。 */
export const strings = {
  common: {
    loading: "載入中…",
    loadFailedShort: "載入失敗",
    loadFailed: "載入失敗，請稍後再試。",
    connectionFailed: "連線失敗，請稍後再試。",
    saveFailed: "儲存失敗，請稍後再試。",
    deleteFailed: "刪除失敗，請稍後再試。",
    cancel: "取消",
    delete: "刪除",
    edit: "編輯",
    create: "新增",
    update: "更新",
    cancelEdit: "取消編輯",
    login: "登入",
    passwordLabel: "密碼",
    passwordPlaceholder: "至少 8 碼",
  },
  nav: {
    role: "選擇身分",
    guardianLogin: "家屬登入",
    guardianRegister: "家屬註冊",
    guardianHome: "我的長輩",
    elderDetail: "長輩詳情",
    medications: "用藥管理",
    appointments: "回診管理",
    notifications: "通知",
    elderBind: "輸入綁定碼",
    elderLogin: "長輩登入",
  },
  role: {
    brand: "金孫",
    slogan: "聽懂國台語的長輩陪伴守護",
    iAmElder: "我是長輩",
    iAmGuardian: "我是家屬",
    // RoleSwitcher（內測切換器）標籤
    switchToElder: "切換到長輩端（內測）",
    switchToGuardian: "切換到家屬端（內測）",
  },
  elderBind: {
    inviteNotFound: "找不到這組號碼，請跟家人再確認一次。",
    inviteUsed: "這組號碼已經用過了，請家人重新產生一組。",
    inviteExpired: "這組號碼過期了，請家人重新產生一組。",
    tooManyAttempts: "試太多次了，請家人重新產生一組。",
    bindFailed: "連不上金孫，請稍後再試一次。",
    cameraPermission: "需要相機權限才能掃描，也可以直接輸入號碼。",
    scanHint: "把家人給的方塊圖對準框框",
    switchToManual: "改用輸入號碼",
    hint: "掃描家人給的方塊圖，或輸入號碼",
    scanQr: "掃描 QR 碼",
    codePlaceholder: "綁定碼",
    start: "開始使用",
    loginLink: "用過金孫？帳號密碼登入",
  },
  elderLogin: {
    notPaired: "這支手機還沒跟家人配對過，請先請家人給您綁定圖（QR）掃描一次。",
    wrongCredentials: "號碼或密碼不對，可以請家人幫忙確認。",
    hint: "輸入家人幫您設定的手機號碼和密碼，登入一次就會一直記住。",
    phoneLabel: "手機號碼",
  },
  talk: {
    idleHint: "按住下面的大按鈕，跟金孫說話",
    fallback: "金孫沒聽清楚，再說一次好嗎？",
    micPermission: "需要麥克風權限才能跟金孫說話，請到設定開啟。",
    listening: "金孫在聽…",
    thinking: "金孫想一下…",
    bindingLost: "這台手機的綁定失效了，請家人重新給您一組號碼。",
    pressToTalk: "按住說話",
    releaseToSend: "放開就送出",
    logout: "登出",
    logoutConfirmTitle: "登出",
    logoutConfirmBody: "確定要登出嗎？下次要用手機號碼和密碼再登入。",
    logoutCancel: "取消",
  },
  guardianLogin: {
    wrongCredentials: "帳號或密碼不對，請再試一次。",
    registerLink: "還沒有帳號？註冊",
  },
  guardianRegister: {
    passwordTooShort: "密碼至少 8 碼。",
    emailTaken: "這個 Email 已經註冊過了，請直接登入。",
    nameLabel: "您的稱呼",
    namePlaceholder: "例如：兒子小明",
    submit: "註冊並登入",
  },
  guardianHome: {
    nameRequired: "請先輸入長輩的稱呼。",
    addFailed: "新增失敗",
    logout: "登出",
    logoutConfirm: "確定要登出嗎？",
    notify: "通知",
    addElderSection: "新增長輩",
    elderNameLabel: "長輩稱呼",
    elderNamePlaceholder: "例如：阿公",
    // 多行 JSX 文字節點：換行處由 JSX 收斂成單一空白，這裡以字串串接保留同樣的間隔。
    consent:
      "建立後，金孫會記錄長輩與它的對話內容（文字與語音），用來陪伴關懷、產生每日摘要、" +
      " 偵測到危急狀況時通知家人；資料會一直保留，開發團隊為了改善服務可檢視內容。" +
      " 按下「建立長輩檔案」即代表您替長輩同意以上事項。",
    createElder: "建立長輩檔案",
    inviteHint: "長輩綁定碼（在長輩手機輸入或掃描一次即可）：",
    copyCode: "複製綁定碼",
    copiedTitle: "已複製",
    copiedMessage: "綁定碼已複製，可貼給家人或長輩。",
    empty: "還沒有長輩檔案，先在上面建立一位吧。",
  },
  elderDetail: {
    accountSaved: "已設定完成。長輩手機用這組號碼＋密碼登入一次就會一直記住。",
    accountSaveFailed: "設定失敗，請稍後再試。",
    inviteFailed: "產生邀請碼失敗",
    healthReportSection: "健康報告（近 30 天）",
    noRiskEvents: "沒有危急事件，一切平安。",
    remindersCount: (count: number) => `近 30 天提醒 ${count} 則`,
    dailySummarySection: "每日摘要",
    noSummaries: "還沒有摘要——長輩與金孫聊過天後，隔天早上就會出現。",
    medicationsSection: "固定用藥",
    noMedications: "還沒有用藥，點下方「管理用藥」新增。",
    manageMedications: "管理用藥",
    upcomingAppointmentsSection: "即將回診",
    noAppointments: "沒有排定的回診。",
    manageAppointments: "管理回診",
    accountSection: "長輩登入帳密（代辦）",
    // 多行 JSX 文字節點：換行處由 JSX 收斂成單一空白，這裡以字串串接保留同樣的間隔。
    accountHelp:
      "幫長輩設定手機號碼＋密碼。換手機或登出後，長輩用這組帳密登入即可，不用再掃碼；" +
      " 忘記密碼時在這裡重設一次就好。",
    accountPhoneLabel: "長輩手機號碼",
    accountPasswordLabel: "密碼（至少 8 碼）",
    saveAccount: "儲存帳密",
    inviteSection: "邀請其他家屬",
    makeInvite: "產生家屬邀請碼",
  },
  medications: {
    deleteTitle: "刪除用藥",
    confirmDelete: (name: string) => `確定要刪除「${name}」嗎？`,
    listSection: "固定用藥",
    empty: "還沒有用藥，從下方新增第一筆。",
    editSection: "編輯用藥",
    addSection: "新增用藥",
    nameLabel: "藥名",
    namePlaceholder: "例：降血壓藥",
    slotsLabel: "提醒時段（可複選）",
  },
  appointments: {
    deleteTitle: "刪除回診",
    confirmDelete: (shown: string, label: string) => `確定要刪除「${shown}｜${label}」嗎？`,
    listSection: "已排定回診",
    empty: "沒有排定的回診，從下方新增第一筆。",
    editSection: "編輯回診",
    addSection: "新增回診",
    dateLabel: "回診日期",
    datePlaceholder: "點這裡選日期",
    timeLabel: "看診時間（選填）",
    timePlaceholder: "點這裡選時間（提醒會帶上）",
    contentLabel: "回診內容",
    contentPlaceholder: "例：心臟科回診 林口長庚",
  },
  notifications: {
    empty: "目前沒有通知。金孫有事會第一時間放在這裡。",
  },
} as const;
