"""候選衛教資料來源清冊。

這份清冊只保存治理狀態；是否實際抓取仍需通過 SourceValidator。
"""

from __future__ import annotations

from collections.abc import Iterable

from kinsun.rag.schemas import (
    CopyrightStatus,
    RecommendedStatus,
    Source,
    SourceType,
    TrustLevel,
)

DEFAULT_SOURCES: tuple[Source, ...] = (
    Source(
        "hpa_elder_health",
        "銀髮族健康",
        "https://www.hpa.gov.tw/Pages/List.aspx?nodeid=39",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        True,
        ("hpa.gov.tw",),
        "官方長者衛教入口。",
    ),
    Source(
        "hpa_elder_chronic",
        "老人健康促進及慢性疾病防治",
        "https://www.hpa.gov.tw/Pages/List.aspx?nodeid=40",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        True,
        ("hpa.gov.tw",),
        "官方老人健康與慢性病衛教入口。",
    ),
    Source(
        "hpa_chronic_disease",
        "慢性病防治",
        "https://www.hpa.gov.tw/Pages/List.aspx?nodeid=46",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        True,
        ("hpa.gov.tw",),
        "官方慢性病防治衛教入口。",
    ),
    Source(
        "hpa_handbooks",
        "健康手冊專區",
        "https://www.hpa.gov.tw/Pages/EBookList.aspx?nodeid=53",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("hpa.gov.tw",),
        "PDF／電子書需逐本確認解析品質與版本。",
    ),
    Source(
        "hpa_posters_leaflets",
        "衛教宣導海報及單張專區",
        "https://www.hpa.gov.tw/Pages/EBookList.aspx?nodeid=54",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("hpa.gov.tw",),
        "圖片型素材與 PDF 需人工確認。",
    ),
    Source(
        "hpa_faq",
        "常見問答",
        "https://www.hpa.gov.tw/Pages/List.aspx?nodeid=80",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        True,
        ("hpa.gov.tw",),
        "官方 FAQ，適合一般民眾理解。",
    ),
    Source(
        "health99",
        "健康九九＋",
        "https://health99.hpa.gov.tw/",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("health99.hpa.gov.tw",),
        "入口包含影音、圖片與下載素材，需逐件審查。",
    ),
    Source(
        "mohw_health_window",
        "衛教視窗",
        "https://www.mohw.gov.tw/np-34-1.html",
        "衛生福利部",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        True,
        ("mohw.gov.tw",),
        "衛福部官方衛教入口。",
    ),
    Source(
        "mohw_health_article",
        "衛福部衛教內容頁",
        "https://www.mohw.gov.tw/cp-88-210-1.html",
        "衛生福利部",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        True,
        ("mohw.gov.tw",),
        "需於 ingestion 時驗證單頁 metadata。",
    ),
    Source(
        "mohw_health_list",
        "衛福部衛教列表",
        "https://www.mohw.gov.tw/lp-88-1-40.html",
        "衛生福利部",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        False,
        ("mohw.gov.tw",),
        "適合 discovery，不直接作回答來源。",
    ),
    Source(
        "cdc_home",
        "疾病管制署入口",
        "https://www.cdc.gov.tw/",
        "衛生福利部疾病管制署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.CONDITIONAL,
        False,
        ("cdc.gov.tw",),
        "傳染病資訊高度時效敏感，需 topic whitelist。",
    ),
    Source(
        "cdc_advocacy",
        "CDC 宣導",
        "https://www.cdc.gov.tw/Advocacy",
        "衛生福利部疾病管制署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("cdc.gov.tw",),
        "素材授權與解析品質需逐件確認。",
    ),
    Source(
        "fda_home",
        "食品藥物管理署入口",
        "https://www.fda.gov.tw/",
        "衛生福利部食品藥物管理署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.CONDITIONAL,
        False,
        ("fda.gov.tw",),
        "需 topic whitelist，禁止用於用藥調整建議。",
    ),
    Source(
        "hpa_news_api",
        "HPA 新聞 API",
        "https://www.hpa.gov.tw/wf/newsapi.ashx",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.CONDITIONAL,
        False,
        ("hpa.gov.tw",),
        "JSON 可抓取，但新聞不等於穩定衛教。",
    ),
    Source(
        "hpa_rss_index",
        "HPA RSS 專區",
        "https://www.hpa.gov.tw/Pages/List.aspx?nodeid=1348",
        "衛生福利部國民健康署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        False,
        ("hpa.gov.tw",),
        "只作更新偵測。",
    ),
    Source(
        "cdc_rss",
        "CDC RSS",
        "https://www.cdc.gov.tw/RSS",
        "衛生福利部疾病管制署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.APPROVED,
        False,
        ("cdc.gov.tw",),
        "只作更新偵測。",
    ),
    Source(
        "fda_open_data",
        "FDA open data API",
        "https://data.fda.gov.tw/",
        "衛生福利部食品藥物管理署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.CONDITIONAL,
        False,
        ("data.fda.gov.tw",),
        "需逐 dataset 確認是否屬衛教。",
    ),
    Source(
        "nhi_open_page",
        "健保署資料開放頁",
        "https://www.nhi.gov.tw/ch/np-3036-1.html",
        "衛生福利部中央健康保險署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("nhi.gov.tw",),
        "本次驗證回 403，且內容多偏行政資料。",
    ),
    Source(
        "nhi_iode",
        "健保署資料開放平台",
        "https://info.nhi.gov.tw/IODE0000/IODE0000S01",
        "衛生福利部中央健康保險署",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.OUT_OF_SCOPE,
        False,
        ("info.nhi.gov.tw",),
        "偏行政與給付資料，不進衛教 RAG 第一批。",
    ),
    Source(
        "data_gov_tw",
        "政府資料開放平臺",
        "https://data.gov.tw/",
        "國家發展委員會／各資料提供機關",
        SourceType.GOVERNMENT,
        TrustLevel.MEDIUM,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.CONDITIONAL,
        False,
        ("data.gov.tw",),
        "只作 dataset discovery。",
    ),
    Source(
        "data_gov_m2m",
        "政府資料開放 M2M",
        "https://data.gov.tw/m2m",
        "國家發展委員會／各資料提供機關",
        SourceType.GOVERNMENT,
        TrustLevel.MEDIUM,
        CopyrightStatus.ALLOWED,
        RecommendedStatus.CONDITIONAL,
        False,
        ("data.gov.tw",),
        "只作 API discovery。",
    ),
    Source(
        "vghtpe_ihealth",
        "北榮健康 e 點通",
        "https://ihealth.vghtpe.gov.tw/",
        "臺北榮民總醫院",
        SourceType.HOSPITAL,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("ihealth.vghtpe.gov.tw",),
        "本次驗證首頁回 403，需人工確認授權與 URL。",
    ),
    Source(
        "ntuh_epaper",
        "臺大醫院健康電子報",
        "https://epaper.ntuh.gov.tw/health/",
        "國立臺灣大學醫學院附設醫院",
        SourceType.HOSPITAL,
        TrustLevel.HIGH,
        CopyrightStatus.DISALLOWED,
        RecommendedStatus.REJECTED,
        False,
        ("epaper.ntuh.gov.tw",),
        "未取得再利用授權前不可 ingestion。",
    ),
    Source(
        "cgmh",
        "長庚醫療財團法人",
        "https://www.cgmh.org.tw/",
        "長庚醫療財團法人",
        SourceType.HOSPITAL,
        TrustLevel.HIGH,
        CopyrightStatus.DISALLOWED,
        RecommendedStatus.REJECTED,
        False,
        ("cgmh.org.tw",),
        "首頁標示未經授權禁止轉載。",
    ),
    Source(
        "cmuh",
        "中國醫藥大學附設醫院",
        "https://www.cmuh.cmu.edu.tw/",
        "中國醫藥大學附設醫院",
        SourceType.HOSPITAL,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("cmuh.cmu.edu.tw",),
        "候選入口，需人工確認衛教頁與授權。",
    ),
    Source(
        "vghtc",
        "臺中榮民總醫院",
        "https://www.vghtc.gov.tw/",
        "臺中榮民總醫院",
        SourceType.HOSPITAL,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("vghtc.gov.tw",),
        "候選入口，需人工確認衛教頁與授權。",
    ),
    Source(
        "medlineplus",
        "MedlinePlus",
        "https://medlineplus.gov/",
        "U.S. National Library of Medicine",
        SourceType.GOVERNMENT,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("medlineplus.gov",),
        "國際補充來源，英文與授權需逐項確認。",
    ),
    Source(
        "who_health_topics",
        "WHO Health Topics",
        "https://www.who.int/health-topics",
        "World Health Organization",
        SourceType.INTERNATIONAL_OFFICIAL,
        TrustLevel.HIGH,
        CopyrightStatus.NEEDS_REVIEW,
        RecommendedStatus.CONDITIONAL,
        False,
        ("who.int",),
        "CC BY-NC-SA 3.0 IGO 與翻譯條件需法務確認。",
    ),
)


class SourceRegistry:
    def __init__(self, sources: Iterable[Source] = DEFAULT_SOURCES) -> None:
        self._sources = {source.source_id: source for source in sources}

    def get(self, source_id: str) -> Source:
        return self._sources[source_id]

    def all(self) -> tuple[Source, ...]:
        return tuple(self._sources.values())

    def approved_for_rag(self) -> tuple[Source, ...]:
        return tuple(source for source in self._sources.values() if source.approved_for_rag)
